services:
  app:
    container_name: wealthy-app
    build: .
    restart: unless-stopped
    networks:
      - ubuntu_caddy
      - wealthy-bot_wealthy

networks:
  ubuntu_caddy:
    external: true
  wealthy-bot_wealthy:
    external: true