services:
  app:
    container_name: wealthy-app
    build: .
    restart: unless-stopped
    networks:
      - ubuntu_caddy
      - ubuntu_wealthy

networks:
  ubuntu_caddy:
    external: true
  ubuntu_wealthy:
    external: true